name: Main

on:
  push:
    branches: ["master"]
    tags: ["*"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: CMake
        id: cmake-install
        uses: thezhe/cmake-install@master

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{github.event.repository.name}}_${{runner.os}}
          path: ${{steps.cmake-install.outputs.install-directory}}

  release:
    if: ${{github.ref_type == 'tag'}}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4.1.0

      - name: Zip Artifacts
        run: for i in */; do zip -r "${i%/}.zip" "$i"; done

      - name: Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "*.zip"
