name: Main

on:
  push:
    branches: ['master']
    tags: ['*']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
        - name: test
          run: ls -Force || ls -a
#       - name: Checkout
#         uses: actions/checkout@v4.1.1

#       - name: CMake
#         run: cmake --workflow --preset default

#       - name: Upload Artifact
#         uses: actions/upload-artifact@v3.1.3
#         with:
#           name: ${{github.event.repository.name}}_${{runner.os}}
#           path: ./build/install

#   release:
#     if: ${{github.ref_type == 'tag'}}
#     needs: build
#     runs-on: ubuntu-latest
#     permissions:
#         contents: write
#     steps:
#       - name: Download Artifacts
#         uses: actions/download-artifact@v3.0.2
#         with:
#             path: artifacts

#       - name: GH Release Create
#         run: gh release create --notes-from-tag ./*
#         working
#         env:
#             GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
